### PR TITLE
Script for installing some prerequisites for a DC/OS Cluster

### PR DESCRIPTION
**Pull request by kaitcart-zz**

### CODE REVIEW

**Comment by mattj-io** [comment]
LGTM - one small thing though, could you add a comment describing what this script is for ? I suspect more things will end up in this repository over time, and will make it easier to track

**Comment by kaitcart-zz** [comment]
@mattj-io I added a brief description. Let me know if anything else needs to be updated.

**Comment by mattj-io** [comment]
Thanks @kaitcart - I was actually thinking more what it's purpose is, is this connected to preparing machines for training sessions ? If so, could you just add that to the comment

**Comment by mattj-io** [comment]
👍

**Pull request merged**
